# Generated by Django 6.0.2 on 2026-03-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, help_text="Введите Ваша страна", max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(help_text="Введите Ваша почта", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, help_text="Введите Ваш номер телефона", max_length=15, null=True),
        ),
    ]
