# Generated by Django 6.0.3 on 2026-03-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_country_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
    ]
