# Generated by Django 6.0.2 on 2026-02-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите название заголовок", max_length=200, verbose_name="заголовок"),
                ),
                ("content", models.TextField(help_text="Введите содержимое", verbose_name="содержимое")),
                ("img", models.ImageField(blank=True, null=True, upload_to="images/blogs", verbose_name="превью")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("is_active", models.BooleanField(default=True, verbose_name="признак публикации")),
                ("viewcount", models.IntegerField(default=0, verbose_name="количество просмотров")),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ["title"],
            },
        ),
    ]
