# Generated by Django 6.0.2 on 2026-02-11 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Ведите название продукта", max_length=150, verbose_name="Наименование"
                    ),
                ),
                ("description", models.TextField(help_text="Введите описание продукта", verbose_name="Описание")),
                ("img", models.ImageField(blank=True, null=True, upload_to="images/products")),
                (
                    "category",
                    models.CharField(help_text="Введите категория продукта", max_length=150, verbose_name="Категория"),
                ),
                ("price", models.FloatField(help_text="Введите цена продукта", verbose_name="цена")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["name", "category", "price"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название категории", max_length=150, verbose_name="Наименование"
                    ),
                ),
                ("description", models.TextField(help_text="Введите описание категории", verbose_name="Описание")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="продукты", to="catalog.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
    ]
