# Generated by Django 6.0.2 on 2026-02-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Наименование")),
                ("phone", models.CharField(max_length=30, verbose_name="Телефон")),
                ("message", models.TextField(verbose_name="Сообщение")),
            ],
            options={
                "verbose_name": "Данные контакта",
                "verbose_name_plural": "Контактные данные",
            },
        ),
    ]
