# Generated by Django 6.0.2 on 2026-02-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="author",
            new_name="product",
        ),
    ]
