# Generated by Django 6.0.2 on 2026-03-05 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите владельца продукта",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="продукты",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("P", "Pending"), ("A", "Approved"), ("C", "Cancelled"), ("R", "Rejected")],
                default="P",
                max_length=1,
                null=True,
            ),
        ),
    ]
